// ConfigPch.h -- include file for pre-compiled headers
// PCH's should work with MSFT's Visual Studio and
// Apple's XCode.
//////////////////////////////////////////////////////////////////

#ifndef H_CONFIG_PCH_H
#define H_CONFIG_PCH_H

#include <wx/wxprec.h>
#ifndef  WX_PRECOMP
#   include <wx/wx.h>
#endif //precompiled headers
#include <wx/archive.h>
#include <wx/artprov.h>
#include <wx/bmpbuttn.h>
#include <wx/busyinfo.h>
#include <wx/clipbrd.h>
#include <wx/cmdline.h>
#include <wx/cmndata.h>
#include <wx/colordlg.h>
#include <wx/combobox.h>
#include <wx/config.h>
#include <wx/cshelp.h>
#include <wx/dataobj.h>
#include <wx/dc.h>
#include <wx/dcbuffer.h>
#include <wx/dcprint.h>
#include <wx/dir.h>
#include <wx/datstrm.h>
#include <wx/display.h>
#include <wx/dynarray.h>
#include <wx/dnd.h>
#include <wx/ffile.h>
#include <wx/file.h>
#include <wx/filefn.h>
#include <wx/filename.h>
#include <wx/filepicker.h>
#include <wx/fontdlg.h>
#include <wx/fontenum.h>
#include <wx/fontmap.h>
#include <wx/fs_arc.h>
#include <wx/fs_mem.h>
#include <wx/fs_zip.h>
#include <wx/gdicmn.h>
#include <wx/help.h>
#include <wx/helpbase.h>
#include <wx/helpwin.h>
#if defined(__WXMSW__)
#include <wx/msw/helpchm.h>
#endif
//#if defined(__WXGTK__) || defined(__WXMAC__)
// TODO decide what kind of help we want for GTK and MAC
//#include <wx/generic/helpext.h>	// external HTML help browser
//#include <wx/html/helpctrl.h>
//#endif
#include <wx/html/htmlwin.h>
#include <wx/imaglist.h>
#include <wx/image.h>
#include <wx/listbook.h>
#include <wx/listctrl.h>
#include <wx/msgout.h>
#include <wx/mstream.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/print.h>
#include <wx/printdlg.h>
#include <wx/progdlg.h>
#include <wx/propdlg.h>
#include <wx/protocol/http.h>
#include <wx/regex.h>
#include <wx/settings.h>
#include <wx/socket.h>
#include <wx/spinctrl.h>
#include <wx/splash.h>
#include <wx/splitter.h>
//#include "../Config/wx_proportional_splitter.h"
#include <wx/statline.h>
#include <wx/strconv.h>
#include <wx/stream.h>
#include <wx/sstream.h>
#include <wx/sysopt.h>
#include <wx/tglbtn.h>
#include <wx/thread.h>
#include <wx/tokenzr.h>
#include <wx/treectrl.h>
#include <wx/utils.h>
#include <wx/valgen.h>
#include <wx/valnum.h>
#include <wx/valtext.h>
#include <wx/wfstream.h>

#if wxCHECK_VERSION(2,8,0)
#include <wx/treebook.h>
#endif

#ifdef __WXMSW__
# pragma warning(push)
# pragma warning(disable:4702)		// silence unreachable code warning in MSFT's STL headers
#endif

#include <list>
#include <map>
#include <set>
#include <vector>

#ifdef __WXMSW__
# pragma warning(pop)
#endif

#include <GEN_ConfigFeatures.h>		// generated by makefile

#ifdef FEATURE_SHEX
#include <wx/dynlib.h>		// wxWidgets wrapper for loading dll's
#endif

#include <ConfigMacros.h>

#endif//H_CONFIG_PCH_H
